In [1]:
from transformers import AutoModelForCausalLM
import torch

model_path = "/works/data0/yama11235/model/van-work/hf-cache/hub/models--mistralai--Mistral-7B-Instruct-v0.1/snapshots/2dcff66eac0c01dc50e4c41eea959968232187fe"

model = AutoModelForCausalLM.from_pretrained("prometheus-eval/prometheus-7b-v2.0", device_map="auto",torch_dtype=torch.float16)
# model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto",torch_dtype=torch.float16)

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

In [2]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("prometheus-eval/prometheus-7b-v2.0")

In [3]:
input_ids = tokenizer.encode_plus("The meaning of life is", return_tensors="pt").input_ids.to(model.device)
out = model.generate(input_ids, max_length=50, do_sample=False)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [5]:
tokenizer.batch_decode(out)

['<s> The meaning of life is a philosophical question that has been debated throughout history. It is a complex issue that involves various aspects such as personal beliefs, scientific theories, and cultural values. The answer to this question is subjective and can vary']

In [3]:
from huggingface_hub import notebook_login

# notebook_loginを実行
notebook_login()
#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

In [4]:
from transformer_lens.hook_points import (
    HookPoint,
)  # Hooking utilities
from transformer_lens import HookedTransformer

hook_model = HookedTransformer.from_pretrained_no_processing(
    "mistral-7b-instruct",
    hf_model=model, 
    # from_pretrained_kwargs={"device_map": "auto"},
    move_to_device=True,
    device=model.device,
    n_devices=4,
    dtype=torch.float16,
)

prometheus-eval/prometheus-7b-v2.0
Loaded pretrained model mistral-7b-instruct into HookedTransformer


In [12]:
from transformer_lens import utils
utils.get_device()

device(type='cuda')

In [28]:
model(tokenizer.encode("today",return_tensors="pt"))

CausalLMOutputWithPast(loss={'logits': tensor([[[-5.0156, -4.9570, -0.2913,  ..., -3.3809, -2.6465, -2.9805],
         [-7.3594, -7.2461, -1.9395,  ..., -7.3906, -6.8789, -6.4102]]]), 'past_key_values': ((tensor([[[[-0.2235,  0.0745,  0.3938,  ..., -1.4082, -1.9980, -2.1406],
          [ 6.1094, -4.5000, -3.0508,  ...,  2.2363,  1.0947,  0.5068]],

         [[ 0.0546,  0.1020,  0.0512,  ...,  3.4941, -3.5977,  1.8330],
          [ 0.2161, -0.4023, -0.0981,  ..., -3.5293,  3.4492, -1.3916]],

         [[ 0.0937, -0.0490,  0.0593,  ..., -0.7808, -0.8096,  0.7959],
          [ 0.0264,  2.5996, -1.9785,  ...,  1.7695,  1.7061, -1.6094]],

         ...,

         [[ 0.0634,  0.0574, -0.1324,  ...,  1.6963, -1.8838,  1.4756],
          [-0.7173,  0.5767, -0.5469,  ..., -1.6377,  2.2129, -1.4609]],

         [[ 0.1943,  0.0981, -0.1869,  ..., -1.1084, -1.1338, -1.6309],
          [ 1.0303, -0.6133, -1.1807,  ...,  0.7827,  0.9263,  3.2402]],

         [[ 0.0309,  0.0191,  0.0088,  ...,  0.856

In [22]:
hook_model("today")

tensor([[[-5.0156, -4.9492, -0.2915,  ..., -3.3750, -2.6426, -2.9766],
         [-7.3438, -7.2344, -1.9424,  ..., -7.4023, -6.9141, -6.4297]]],
       device='cuda:3', dtype=torch.float16, grad_fn=<ViewBackward0>)

In [23]:
hook_model.run_with_cache("today")

(tensor([[[-5.0156, -4.9492, -0.2915,  ..., -3.3750, -2.6426, -2.9766],
          [-7.3438, -7.2344, -1.9424,  ..., -7.4023, -6.9141, -6.4297]]],
        device='cuda:3', dtype=torch.float16, grad_fn=<ViewBackward0>),
 ActivationCache with keys ['hook_embed', 'blocks.0.hook_resid_pre', 'blocks.0.ln1.hook_scale', 'blocks.0.ln1.hook_normalized', 'blocks.0.attn.hook_q', 'blocks.0.attn.hook_k', 'blocks.0.attn.hook_v', 'blocks.0.attn.hook_rot_q', 'blocks.0.attn.hook_rot_k', 'blocks.0.attn.hook_attn_scores', 'blocks.0.attn.hook_pattern', 'blocks.0.attn.hook_z', 'blocks.0.hook_attn_out', 'blocks.0.hook_resid_mid', 'blocks.0.ln2.hook_scale', 'blocks.0.ln2.hook_normalized', 'blocks.0.mlp.hook_pre', 'blocks.0.mlp.hook_pre_linear', 'blocks.0.mlp.hook_post', 'blocks.0.hook_mlp_out', 'blocks.0.hook_resid_post', 'blocks.1.hook_resid_pre', 'blocks.1.ln1.hook_scale', 'blocks.1.ln1.hook_normalized', 'blocks.1.attn.hook_q', 'blocks.1.attn.hook_k', 'blocks.1.attn.hook_v', 'blocks.1.attn.hook_rot_q', 'blo

In [6]:
model(tokenizer.encode("today",return_tensors="pt")).logits

tensor([[[-4.6602, -4.4219, -0.0883,  ..., -3.4590, -2.5039, -3.0449],
         [-7.3945, -6.9453,  3.1348,  ..., -8.1641, -6.7188, -6.0938]]],
       grad_fn=<ToCopyBackward0>)

In [5]:
from transformer_lens.utils import test_prompt

# Test the model with a prompt
test_prompt(
    "The meaning of life is",
    " not",
    hook_model,
    prepend_space_to_answer=False,
)

Tokenized prompt: ['<s>', 'The', 'meaning', 'of', 'life', 'is']
Tokenized answer: ['not']


Performance on answer token:
Rank: 3        Logit: 12.95 Prob:  3.92% Token: |not|

Top 0th token. Logit: 15.84 Prob: 69.97% Token: |a|
Top 1th token. Logit: 13.62 Prob:  7.61% Token: |an|
Top 2th token. Logit: 13.29 Prob:  5.48% Token: |one|
Top 3th token. Logit: 12.95 Prob:  3.92% Token: |not|
Top 4th token. Logit: 12.27 Prob:  1.99% Token: |the|
Top 5th token. Logit: 12.05 Prob:  1.59% Token: |something|
Top 6th token. Logit: 11.77 Prob:  1.19% Token: |often|
Top 7th token. Logit: 11.54 Prob:  0.95% Token: |subject|
Top 8th token. Logit: 10.49 Prob:  0.33% Token: |still|
Top 9th token. Logit: 10.48 Prob:  0.33% Token: |different|


Ranks of the answer tokens: [('not', 3)]

In [5]:
text = "Natural language processing tasks, such as question answering, machine translation, reading comprehension, and summarization, are typically approached with supervised learning on taskspecific datasets."
tokens = hook_model.to_tokens(text)
print(tokens.device)
logits, cache = hook_model.run_with_cache(tokens, remove_batch_dim=True)

cuda:0


In [6]:
print(type(cache))
attention_pattern = cache["pattern", 0, "attn"]
print(attention_pattern.shape)
str_tokens = hook_model.to_str_tokens(text)

<class 'transformer_lens.ActivationCache.ActivationCache'>
torch.Size([32, 34, 34])


In [9]:
import circuitsvis as cv
print("Layer 0 Head Attention Patterns:")
cv.attention.attention_patterns(tokens=str_tokens, attention=attention_pattern)

Layer 0 Head Attention Patterns:


In [13]:
hook_model.to_tokens(example_prompt)

tensor([[    1, 15359, 28725,   910,   460,   368,  2548,   456, 28804,   315,
         28742, 28719,  1528, 16269,   574, 10005]], device='cuda:0')

In [17]:
import circuitsvis as cv  # optional dep, install with pip install circuitsvis

# Let's make a longer prompt and see the log probabilities of the tokens
example_prompt = """Hi, how are you doing this? I'm really enjoying your posts"""
logits, cache = hook_model.run_with_cache(example_prompt)
cv.logits.token_log_probs(
    hook_model.to_tokens(example_prompt),
    hook_model(example_prompt)[0].log_softmax(dim=-1).to("cuda:0"),
    hook_model.to_string,
)
# hover on the output to see the result.